2018-11-29 16:05:11,791 ERROR: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand. [in C:\workspace\Spec2DB_new\Source\collaboration_2\app\api_1_0\api_excel_htm.py:41]
2018-11-29 16:14:23,497 ERROR: 'Flask' object has no attribute 'get_current_objects' [in C:\workspace\Spec2DB_new\Source\collaboration_2\app\api_1_0\api_excel_htm.py:41]
2018-11-29 16:16:16,252 ERROR: 'Flask' object has no attribute 'get_current_objects' [in C:\workspace\Spec2DB_new\Source\collaboration_2\app\api_1_0\api_excel_htm.py:41]
2018-11-29 16:23:32,730 ERROR: 'Flask' object has no attribute 'get_current_objects' [in C:\workspace\Spec2DB_new\Source\collaboration_2\app\api_1_0\api_excel_htm.py:41]
2018-11-29 16:41:49,762 ERROR: [Errno 2] No such file or directory: 'C:\\workspace\\Spec2DB_new\\docs\\spec_excelfunc_2_01_Map (3)_20611_20612.xlsm' [in C:\workspace\Spec2DB_new\Source\collaboration_2\app\api_1_0\api_excel_htm.py:41]
2018-11-29 16:57:17,037 ERROR: [Errno 2] No such file or directory: 'C:\\workspace\\Spec2DB_new\\Source\\collaboration_2\\../../docs/spec_excel/' [in C:\workspace\Spec2DB_new\Source\collaboration_2\app\api_1_0\api_excel_htm.py:42]
2018-11-29 16:59:44,760 ERROR: [Errno 2] No such file or directory: 'C:\\workspace\\Spec2DB_new\\Source\\collaboration_2\\../../docs/spec_excel/' [in C:\workspace\Spec2DB_new\Source\collaboration_2\app\api_1_0\api_excel_htm.py:42]
2018-11-29 17:00:44,126 ERROR: [Errno 2] No such file or directory: 'C:\\workspace\\Spec2DB_new\\docs\\spec_excel\\' [in C:\workspace\Spec2DB_new\Source\collaboration_2\app\api_1_0\api_excel_htm.py:42]
2018-11-29 17:04:38,826 ERROR: [Errno 2] No such file or directory: 'C:\\workspace\\Spec2DB_new\\docs\\spec_excel\\func_2_01_Map (1)_20622_20623.xlsm' [in C:\workspace\Spec2DB_new\Source\collaboration_2\app\api_1_0\api_excel_htm.py:42]
2018-11-29 17:13:59,033 ERROR: [Errno 2] No such file or directory: 'C:/docs/spec_excel/func_2_01_Map (3)_20624_20625.xlsm' [in C:\workspace\Spec2DB_new\Source\collaboration_2\app\api_1_0\api_excel_htm.py:42]
2018-11-29 17:20:01,069 ERROR: x1Html [in C:\workspace\Spec2DB_new\Source\collaboration_2\app\api_1_0\api_excel_htm.py:42]
2018-11-29 17:20:44,642 ERROR: (-2147221008, '尚未调用 CoInitialize。', None, None) [in C:\workspace\Spec2DB_new\Source\collaboration_2\app\api_1_0\api_excel_htm.py:42]
2018-11-29 17:25:31,998 ERROR: x1Html [in C:\workspace\Spec2DB_new\Source\collaboration_2\app\api_1_0\api_excel_htm.py:42]
2018-11-29 17:32:55,242 ERROR: '<win32com.gen_py.Microsoft Excel 15.0 Object Library._Application instance at 0x225348744>' object has no attribute 'WorkBooks' [in C:\workspace\Spec2DB_new\Source\collaboration_2\app\api_1_0\api_excel_htm.py:42]
2018-11-29 17:37:42,932 ERROR: (-2147221008, '尚未调用 CoInitialize。', None, None) [in C:\workspace\Spec2DB_new\Source\collaboration_2\app\api_1_0\api_excel_htm.py:42]
2018-11-29 17:38:17,541 ERROR: This COM object can not automate the makepy process - please run makepy manually for this object [in C:\workspace\Spec2DB_new\Source\collaboration_2\app\api_1_0\api_excel_htm.py:42]
2018-11-29 17:39:30,335 ERROR: This COM object can not automate the makepy process - please run makepy manually for this object [in C:\workspace\Spec2DB_new\Source\collaboration_2\app\api_1_0\api_excel_htm.py:42]
2018-11-29 17:40:24,770 ERROR: This COM object can not automate the makepy process - please run makepy manually for this object [in C:\workspace\Spec2DB_new\Source\collaboration_2\app\api_1_0\api_excel_htm.py:42]
2018-11-29 17:41:47,304 ERROR: This COM object can not automate the makepy process - please run makepy manually for this object [in C:\workspace\Spec2DB_new\Source\collaboration_2\app\api_1_0\api_excel_htm.py:42]
2018-11-29 17:44:28,739 ERROR: (-2147221008, '尚未调用 CoInitialize。', None, None) [in C:\workspace\Spec2DB_new\Source\collaboration_2\app\api_1_0\api_excel_htm.py:42]
2018-11-29 17:46:37,158 ERROR: (-2147221008, '尚未调用 CoInitialize。', None, None) [in C:\workspace\Spec2DB_new\Source\collaboration_2\app\api_1_0\api_excel_htm.py:42]
2018-11-29 17:48:12,428 ERROR: This COM object can not automate the makepy process - please run makepy manually for this object [in C:\workspace\Spec2DB_new\Source\collaboration_2\app\api_1_0\api_excel_htm.py:42]
2018-11-29 18:02:30,405 ERROR: (-2147221008, '尚未调用 CoInitialize。', None, None) [in C:\workspace\Spec2DB_new\Source\collaboration_2\app\api_1_0\api_excel_htm.py:42]
2018-11-29 18:08:07,782 ERROR: (-2147221008, '尚未调用 CoInitialize。', None, None) [in C:\workspace\Spec2DB_new\Source\collaboration_2\app\api_1_0\api_excel_htm.py:42]
2018-11-29 18:09:07,330 ERROR: (-2147221008, '尚未调用 CoInitialize。', None, None) [in C:\workspace\Spec2DB_new\Source\collaboration_2\app\api_1_0\api_excel_htm.py:42]
2018-11-29 18:09:14,924 ERROR: (-2147221008, '尚未调用 CoInitialize。', None, None) [in C:\workspace\Spec2DB_new\Source\collaboration_2\app\api_1_0\api_excel_htm.py:42]
2018-11-29 18:10:02,083 ERROR: (-2147221008, '尚未调用 CoInitialize。', None, None) [in C:\workspace\Spec2DB_new\Source\collaboration_2\app\api_1_0\api_excel_htm.py:42]
2018-11-29 18:10:18,704 ERROR: (-2147221008, '尚未调用 CoInitialize。', None, None) [in C:\workspace\Spec2DB_new\Source\collaboration_2\app\api_1_0\api_excel_htm.py:42]
2018-11-29 18:14:32,073 ERROR: (-2147221008, '尚未调用 CoInitialize。', None, None) [in C:\workspace\Spec2DB_new\Source\collaboration_2\app\api_1_0\api_excel_htm.py:42]
2018-11-29 18:15:05,858 ERROR: (-2147221008, '尚未调用 CoInitialize。', None, None) [in C:\workspace\Spec2DB_new\Source\collaboration_2\app\api_1_0\api_excel_htm.py:42]
